### ISSUE TITLE
New modified exe still running on other pc

### ISSUE THREAD

**Issue by pearlxcore** [Indemos/Copy-Protection#1]
I implement the class, write `Protector.CheckDrive();` on form_load event. Launch the exe, now exe hardcoded with serial number. I try running the modified program on my other laptop but the program still running. It should throw an exception right?

**Comment by artemiusgreat** [comment]
@pearlxcore 

I haven't seen the notification. Correction. At the moment, the tool doesn't throw an exception itself, it only returns the result of the check for the HD serial number. Thus, you app should decide what to do when this check fails. Your code may have  something like this. 

```
if (Equals(Protector.CheckDrive(), "ERROR"))
{
  throw new Exception("Do not copy");
}
```

On the other hand, I probably will simplify and clean up my code a bit and will push a simpler version that will work with exceptions like its described in readme file.

**Comment by artemiusgreat** [comment]
Done. Made some changes and added a [sample](https://github.com/Indemos/Copy-Protection/blob/master/Sample/MainWindow.xaml.cs) WPF app to show how to use it.
