### ISSUE TITLE
Need to explain

### ISSUE THREAD

**Issue by DevX-Cipher** [Indemos/Copy-Protection#2]
need to explain to compile with someone else C# project or something no explaining here

**Comment by artemiusgreat** [comment]
At the moment, there is no nuget package, so the easiest way to include this tool into your project is by copying [this](https://github.com/Indemos/Copy-Protection/blob/master/CopyProtection/Protector.cs) file to your solution and then using it the way it's shown in the [sample](https://github.com/Indemos/Copy-Protection/blob/master/Sample/MainWindow.xaml.cs#L19).

**Comment by DevX-Cipher** [comment]
how do i add someone else hard id or hash to it

**Comment by artemiusgreat** [comment]
If you want to change the ID that will be added to EXE file, you can modify [this](https://github.com/Indemos/Copy-Protection/blob/master/CopyProtection/Protector.cs#L24) variable.

**Comment by DevX-Cipher** [comment]
so i can add a string or hard drive id to it

**Comment by DevX-Cipher** [comment]
i cant seem to add it to my project you got discord or something i can contact you on
